name: buku_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  grpc: ^4.0.1
  postgres: ^2.5.0
  protobuf: ^3.1.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^4.0.0
  protoc_plugin: ^21.1.2
  test: ^1.24.0
